apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: sre-platform
  labels:
    app: prometheus
    app.kubernetes.io/part-of: observability
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http
  type: ClusterIP
