apiVersion: v1
kind: Service
metadata:
  name: incident-engine
  namespace: sre-platform
  labels:
    app: incident-engine
spec:
  selector:
    app: incident-engine
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
