apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: sre-platform
  labels:
    app: alertmanager
    app.kubernetes.io/part-of: observability
spec:
  selector:
    app: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: http
  type: ClusterIP
