apiVersion: v1
kind: Namespace
metadata:
  name: sre-platform
  labels:
    name: sre-platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
